baseURL = 'https://QingSH-J.github.io'
languageCode = 'zh-cn'
title = '调查局档案库'

# Hugo Blox主题配置
[module]
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-plugin-netlify"
  [[module.imports]]
    path = "github.com/HugoBlox/hugo-blox-builder/modules/blox-tailwind"

# Markdown渲染配置
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = "github"
    lineNos = true

# 忽略警告
ignoreLogs = ['warning-goldmark-raw-html']